# Generated by Django 3.1.13 on 2022-04-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211004_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Testing tehehehenn nsns ndna gaga', max_length=250, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Doctor', 'Doctor'), ('Ass. Professor', 'Ass. Professor'), ('Professor', 'Professor')], default='Ass. Professor', max_length=100, verbose_name='Title'),
        ),
    ]
