# Generated by Django 3.1.13 on 2022-04-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220426_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=250, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('Mis.', 'Mis.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Doctor', 'Doctor'), ('Ass. Professor', 'Ass. Professor'), ('Professor', 'Professor')], default='Mr', max_length=100, verbose_name='Title'),
        ),
    ]
