# Generated by Django 3.1.13 on 2022-04-26 22:16

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220427_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Institute',
            field=models.CharField(max_length=200, null=True, verbose_name='Institute or Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Lusaka', max_length=150, null=True, verbose_name='City/District/Town'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile11.png', null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
