# Generated by Django 3.1.13 on 2022-06-27 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220427_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Institute',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=250, verbose_name='bio')),
                ('title', models.CharField(choices=[('Mis.', 'Mis.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Doctor', 'Doctor'), ('Ass. Professor', 'Ass. Professor'), ('Professor', 'Professor')], default='Mr', max_length=100, verbose_name='Title')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='Phone Number')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country')),
                ('city', models.CharField(default='Lusaka', max_length=150, null=True, verbose_name='City/District/Town')),
                ('Institute', models.CharField(max_length=200, null=True, verbose_name='Institute or Company')),
                ('profile_pic', models.ImageField(blank=True, default='profile11.png', null=True, upload_to='', verbose_name='Profile Picture')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('email', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
