# Generated by Django 3.1.13 on 2022-07-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220627_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(max_length=200, null=True, verbose_name='Occupation'),
        ),
    ]
