# Generated by Django 3.1.13 on 2022-07-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(max_length=200, null=True, verbose_name='Postcode'),
        ),
    ]
