# Generated by Django 3.1.13 on 2022-07-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(default='https://www.instagram.com/', max_length=255, verbose_name='LinkeIn'),
        ),
    ]
