# Generated by Django 3.1.13 on 2022-04-26 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20220104_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='del_price',
            field=models.FloatField(default=25000, validators=[django.core.validators.MinValueValidator(9.99)]),
        ),
    ]
