# Generated by Django 3.1.13 on 2022-06-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20220427_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='document',
            field=models.FileField(default=None, upload_to='courses/lessons/documents'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='courses/thumbnails/'),
        ),
    ]
