# Generated by Django 3.1.13 on 2022-06-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20220627_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='document',
            field=models.FileField(upload_to='courses/lessons/documents'),
        ),
    ]
