# Generated by Django 3.1.13 on 2022-06-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20220627_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default='Demo Text', verbose_name='Lesson Content'),
        ),
    ]
