# Generated by Django 3.1.13 on 2022-06-30 20:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 30, 20, 50, 54, 468933, tzinfo=utc), verbose_name='Event Time'),
        ),
    ]
