# Generated by Django 3.1.13 on 2022-06-30 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 30, 20, 51, 38, 198175, tzinfo=utc), verbose_name='Event End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(verbose_name='Event Start Time'),
        ),
    ]
