# Generated by Django 3.1.13 on 2022-06-30 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220630_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 30, 22, 2, 22, 255645, tzinfo=utc), verbose_name='Event End Time'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=350, unique=True),
        ),
    ]
