# Generated by Django 3.1.13 on 2022-07-02 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220702_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 2, 13, 28, 23, 753490, tzinfo=utc), verbose_name='Event End Time'),
        ),
    ]
